name: cicd

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GREMLIN_ENDPOINT: ${{ secrets.GREMLIN_ENDPOINT }}
      GREMLIN_USERNAME: ${{ secrets.GREMLIN_USERNAME }}
      GREMLIN_KEY: ${{ secrets.GREMLIN_KEY }}

      COSMOS_SQL_ENDPOINT: ${{ secrets.COSMOS_SQL_ENDPOINT }}
      COSMOS_SQL_KEY: ${{ secrets.COSMOS_SQL_KEY }}
      COSMOS_SQL_DATABASE: ${{ secrets.COSMOS_SQL_DATABASE }}
      COSMOS_SQL_CONTAINER_VERSIONS: ${{ secrets.COSMOS_SQL_CONTAINER_VERSIONS }}
      COSMOS_SQL_CONTAINER_TOKEN_BLACKLIST: ${{ secrets.COSMOS_SQL_CONTAINER_TOKEN_BLACKLIST }}

      BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
      BLOB_STORAGE_CONTAINER_MESHES: ${{ secrets.BLOB_STORAGE_CONTAINER_MESHES }}
      BLOB_STORAGE_CONTAINER_MATERIALS: ${{ secrets.BLOB_STORAGE_CONTAINER_MATERIALS }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build and test with Maven
        run: mvn clean package

      - name: Rename JAR
        run: mv target/*.jar target/ddditserver.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddditserver
          path: target/ddditserver.jar

      - name: Show build output
        run: ls -lR target

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ddditserver
          path: .

      - name: Show download directory contents
        run: ls -lR .

      - name: Copy JAR to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "./ddditserver.jar"
          target: "/home/${{ secrets.AZURE_VM_USER }}/app/"

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            sudo systemctl restart ddditserver.service
