name: deploy.yml

on:
  workflow_run:
    workflows: [ "java-ci.yml" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # NOTE: Download JAR artifact
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ddditserver
          path: .

      #NOTE: Show download directory
      - name: Debug download directory contents
        run: ls -lR .


        # NOTE: Copy the JAR into VM folder
      - name: Copy JAR to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "./ddditserver.jar"
          target: "/home/${{ secrets.AZURE_VM_USER }}/app/"

      # NOTE: Restart automatically the service on VM
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            sudo systemctl restart ddditserver.service

