name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      actions: read

    steps:
      # NOTE: Show workflow_run.id to check if thew previous workflow is the CI workflow
      - name: Show workflow run ID
        run: |
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"


      # NOTE: Download JAR artifact
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ddditserver
          path: .
          run-id: ${{ github.event.workflow_run.id }}

      #NOTE: Show download directory
      - name: Debug download directory contents
        run: ls -lR .


        # NOTE: Copy the JAR into VM folder
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ddditserver
          path: .
          run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

      # NOTE: Restart automatically the service on VM
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            sudo systemctl restart ddditserver.service

